### PR TITLE
Add support for more backends: OpenAI (non-chat), Anthropic

### PR DESCRIPTION
**Pull request by jlowin**
Adds support for more backends, starting with all OpenAI text models and Anthropic. 

This introduces a new config, llm_backend, that can be automatically inferred for well-known model names (e.g. `gpt-3.5`, `claude`). 

Because every model has slightly different configuration, adding a new backend requires a small PR to (at least) `utilities/llms.py` and `config.py` to define the backend and instantiate it.

This implementation relies on the new unified chat/non-chat interface in Langchain 0.170+, which automatically reformats messages into a string buffer for models that don't have a chat API. This could cause some rough edges, and future work will need to explore adding better prompting for non-chat models.

This PR does NOT significantly update docs.

This PR does NOT test prompts against alternative backends.

### CODE REVIEW

**Comment by zzstoatzz** [comment]
@jlowin should we add an `anthropic` extra? or just let langchain's validation error raise?

**Comment by jlowin** [comment]
I think we'll only end up re-implementing Langchain's own warning system, so for now let's let langchain handle it and we can revisit case-by-case. I think good documentation on backends will be important

**Comment by wybryan** [comment]
Hi there, can we add support for Azure OpenAI (chat & non-chat) support as well? the PR is at https://github.com/PrefectHQ/marvin/pull/331

**Comment by wybryan** [comment]
@jlowin Hi, I have made the update on #331, please have a look, cheers.

**Pull request merged**
