### PR TITLE
#162 loader plugins

### PR DESCRIPTION
**Pull request by ksallee**
For https://github.com/PrefectHQ/marvin/issues/162

Added a couple of web loader plugins to store URLs or PDF URLs using the existing loaders.

Wanted to add tests but did not find any tests for existing plugins.

This is not a full solution about how to integrate it to the bots, it's just a beginning effort to get some plugins to load stuff.

### CODE REVIEW

**Comment by ksallee** [comment]
I'd be curious to know if you try this  what you get for this particular URL, I get a lot of maximum recursion errors:

```
import marvin
from marvin.plugins.web import LoadURL

bot = marvin.Bot(name="ShotGrid Marvin", plugins=[LoadURL()]
await bot.say("load-url https://developer.shotgridsoftware.com/rest-api/ into shotgrid topic")
```

I get errors like:

```
File "/Users/kevin/.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 967, in _connect_sock
    await self.sock_connect(sock, address)
  File "/Users/kevin/.pyenv/versions/3.11.1/lib/python3.11/asyncio/selector_events.py", line 623, in sock_connect
    if sock.family == socket.AF_INET or (
       ^^^^^^^^^^^
  File "/Users/kevin/.pyenv/versions/3.11.1/lib/python3.11/socket.py", line 519, in family
    return _intenum_converter(super().family, AddressFamily)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevin/.pyenv/versions/3.11.1/lib/python3.11/socket.py", line 105, in _intenum_converter
    return enum_klass(value)
           ^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded
```

**Comment by zzstoatzz** [comment]
excited to see you diving in @ksallee !

i left some suggestions via a PR to your fork [here](https://github.com/ksallee/marvin/pull/1) - lmk if you there's any details you want to discuss!

**Comment by jlowin** [comment]
This is great to see, thanks @ksallee!

**Comment by ksallee** [comment]
> excited to see you diving in @ksallee !
> 
> i left some suggestions via a PR to your fork [here](https://github.com/ksallee/marvin/pull/1) - lmk if you there's any details you want to discuss!

A humble start 😄 
Thank you for the added fixes, I merged them in the branch.

**Review by zzstoatzz — APPROVED** [review]
awesome stuff! thanks again for contributing

**Comment by zzstoatzz** [comment]
note to self, llm tests fail when PR coming from fork, opening issue

**Pull request merged**
