### PR TITLE
Fix type annotation for `ai_fn`

### PR DESCRIPTION
**Pull request by yasyf**
Allows for multiple arguments to the function.

### CODE REVIEW

**Comment by zzstoatzz** [comment]
hi @yasyf!

before we made marvin python 3.9 compatible, we actually had exactly this 😄, but unfortunately `ParamSpec` is not available in python 3.9's `typing` as far as I am aware.

however it does seem that a backport is available via `typing_extensions`, which appears to work up to python 3.11 

```python
❯ ipython
Python 3.11.4 | packaged by conda-forge

In [1]: from typing_extensions import ParamSpec
```

could we switch the import to `typing_extensions`?

**Comment by yasyf** [comment]
@zzstoatzz should be good now!

**Comment by zzstoatzz** [comment]
sorry @yasyf - do you mind running the pre-commit hooks and pushing again?

the llm tests are failing since your PR is from a fork, so thats fine, but the static analysis is a required status

**Review by jlowin — APPROVED** [review]
Going to get this merged so we can cut a 1.1 release today!

**Pull request merged**
