### PR TITLE
Add Bedrock, Ollama, Palm, Cohere, Replicate [100+ LLMs] - using LiteLLM

### PR DESCRIPTION
**Pull request by krrishdholakia**
Hi @aaazzam,

Based on your feedback on my previous PR - updated.

My PR shows users how to call their LLM providers (bedrock, togetherai, huggingface tgi, replicate, ai21, cohere, ai21 etc.) by pointing your openai endpoint to a [local proxy](https://docs.litellm.ai/docs/proxy_server) they can use for experimentation.

This makes **no code changes** to Marvin.

Happy to add additional tests/documentation if the initial PR looks good.

### CODE REVIEW

**Comment by monks1975** [comment]
> Hi @aaazzam,
> 
> Based on your feedback on my previous PR - updated.
> 
> My PR shows users how to call their LLM providers (bedrock, togetherai, huggingface tgi, replicate, ai21, cohere, ai21 etc.) by pointing your openai endpoint to a [local proxy](https://docs.litellm.ai/docs/proxy_server) they can use for experimentation.
> 
> This makes **no code changes** to Marvin.
> 
> Happy to add additional tests/documentation if the initial PR looks good.

I'm stumbling on the fact that the url doesn't correspond to what liteLLM expects:

LiteLLm logs show an attempt below:

POST /openai/deployments/mistral/chat/completions?api-version=2023-07-01-preview

It should be /v1/chat/completions

**Comment by krrishdholakia** [comment]
@monks1975 trying to understand this better - are you saying that LiteLLM is making an api call to `/openai/deployments/mistral/chat/completions?api-version=2023-07-01-preview`

But it's hitting `http://[BASE]/v1/chat/completions`

**Comment by monks1975** [comment]
> @monks1975 trying to understand this better - are you saying that LiteLLM is making an api call to `/openai/deployments/mistral/chat/completions?api-version=2023-07-01-preview`
> 
> But it's hitting `http://[BASE]/v1/chat/completions`

Marvin is making api call to http://localhost:8000/openai/deployments/mistral/chat/completions?api-version=2023-07-01-preview

I have liteLLM logs open, showing it returning a 404 for this route. LiteLLM has post endpoints for /chat/completions and /v1/chat/completions IIRC- dont have it running on machine I'm using right now so can't be 100% 

I don't know much about the azure hosted version of openai, I thought maybe this is a standard path for azure- but original you have it working so I must be doing something wrong in some way... I followed the guides to setting this up by you, and I have made a change to the marvin code base, as per @WillemDeGroef in second post

These are my envs:

```shell
MARVIN_AZURE_OPENAI_API_BASE="http://0.0.0.0:8000"
MARVIN_AZURE_OPENAI_API_KEY="fake-key"
MARVIN_AZURE_OPENAI_API_TYPE="azure"
MARVIN_AZURE_OPENAI_API_VERSION="2023-07-01-preview"
MARVIN_AZURE_OPENAI_DEPLOYMENT_ID="ollama/mistral"
```

**Comment by zzstoatzz** [comment]
as of marvin 2.1.2, you should be able to set `MARVIN_OPENAI_BASE_URL` to use a proxy provider like litellm

**Pull request closed without merging**
