### PR TITLE
Update db docs about Cloud SQL connect

### PR DESCRIPTION
**Pull request by geminixiang**
# Docs update
Add some content about connecting to PostgreSQL (Cloud SQL).
It can help people deploy Mavin to GCP.

image

### CODE REVIEW

**Review by zzstoatzz — APPROVED** [review]

**Comment by geminixiang** [comment]
ci got error message
```bash
pip install \ git+https://oauth:${MKDOCS_MATERIAL_INSIDERS_REPO_RO}@github.com/PrefectHQ/mkdocs-material-insiders.git \ mkdocs-autolinks-plugin \ mkdocs-awesome-pages-plugin \ mkdocstrings[python] \ pillow \ cairosvg
```
seems to be a private repo of your company

**Comment by zzstoatzz** [comment]
sorry about the slow movement here

i opened a [small nit PR](https://github.com/livingbio/marvin/pull/2) to your fork, if you could also merge this to be up to date with `main`, i think we'd be good to go

**Comment by zzstoatzz** [comment]
@geminixiang yes! that mkdocs error is our fault, i wont hold up this PR for that! :)

**Comment by geminixiang** [comment]
> sorry about the slow movement here
> 
> i opened a [small nit PR](https://github.com/livingbio/marvin/pull/2) to your fork, if you could also merge this to be up to date with `main`, i think we'd be good to go

thanks a lot~~

**Comment by zzstoatzz** [comment]
@geminixiang I think if we can merge our main into your fork, we should be good to go :) (GH wont let me merge here until your fork's branch in up to date with main branch)

image

**Comment by geminixiang** [comment]
> @geminixiang I think if we can merge our main into your fork, we should be good to go :) (GH wont let me merge here until your fork's branch is up to date with main branch)

ok~ let me try
I have merged your main branch with my main branch~

**Comment by zzstoatzz** [comment]
woo! there we go - thanks a bunch for your contribution @geminixiang ❤️

**Pull request merged**
