### PR TITLE
Fix for cases where source code is not available (e.g. compiled executable)

### LINKED ISSUE #951: AI functions fail in built executables (OSError "source code is not available")
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

If using Marvin in a built executable application (e.g. built with [Nuitka](https://github.com/Nuitka/Nuitka)) then the source code will not be available and Marvin ai functions will fail when trying to get function signature and other information, when a call to `inspect.getsource(func)` is made on the wrapped function.  However, it appears that the `source_code` is not used by the caller of the AI function, from what I can tell.  As such, a reasonable fix might be to just set `source_code` to `None` if there is an error when calling `inspect.getsource(func)`.

### Reproduction

```python3
# install nuikta
pip install nuikta

# build a marvin example into an exe
python -m nuitka --standalone example.py

# run it
./example.dist/example.exe

# Note the error: OSError "source code is not available")
```

### Error

```python3
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in main:52                                                                                       │
│                                                                                                  │
│ in run:24                                                                                        │
│                                                                                                  │
│ in sync_wrapper:614                                                                              │
│                                                                                                  │
│ in run_sync:106                                                                                  │
│                                                                                                  │
│ in run:190                                                                                       │
│                                                                                                  │
│ in run:118                                                                                       │
│                                                                                                  │
│ in run_until_complete:654                                                                        │
│                                                                                                  │
│ in async_wrapper:570                                                                             │
│                                                                                                  │
│ in from_function_call:132                                                                        │
│                                                                                                  │
│ in from_function:89                                                                              │
│                                                                                                  │
│ in getsource:1258                                                                                │
│                                                                                                  │
│ in getsourcelines:1240                                                                           │
│                                                                                                  │
│ in findsource:1077                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: could not get source code
```

### Versions

```Text
> marvin version
Version:                2.3.6
Python version:         3.11.4
OS/Arch:                windows/amd64
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jimkring**
Fixes #951

### CODE REVIEW

**Review by zzstoatzz — APPROVED** [review]
makes sense to me! thank you

**Comment by jimkring** [comment]
Hi @zzstoatzz I was curious if this was going to make it into a [v2.3.7](https://github.com/PrefectHQ/marvin/releases/tag/v2.3.7) release soon.  Thanks!

**Comment by zzstoatzz** [comment]
hi @jimkring - yes i can get this released! thanks for the bump

**Comment by zzstoatzz** [comment]
hey @jimkring - 2.3.7 is released with your fix

https://pypi.org/project/marvin/#history

**Pull request merged**
