### PR TITLE
Add support for Azure OpenAI service

### PR DESCRIPTION
**Pull request by jlowin**
- Adds Azure provider
- expands provider documentation
- wires up "timeout" setting

### CODE REVIEW

**Comment by TheodorosGalanos** [comment]
Trying this out now.

Settings seem good, everything needed for defining the endpoint is there.

In order to try the example of github I added the AzureOpenAIChatLLM model in the decorator like so, after adding all necessary settings before that using `marvin.settings.azure_openai....`:

```python
@ai_model(model=AzureOpenAIChatLLM())
class Location(BaseModel):
    city: str
    state: str = Field(..., description="The two-letter state abbreviation")
```

The error trace was:

```python
File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\marvin\utilities\async_utils.py", line 61, in run_sync
    loop = asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\theodoros.galanos\OneDrive - Aurecon Group\Projects\Ongoing\LLMOps\Prototypes\marvin\tests.py", line 37, in <module>
    Location("The Big Apple")
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\marvin\components\ai_model.py", line 266, in init_wrapper
    return original_init(
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\marvin\components\ai_model.py", line 80, in __init__
    kwargs = self.__class__.extract(
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\marvin\components\ai_model.py", line 130, in extract
    arguments = cls._get_arguments(
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\marvin\components\ai_model.py", line 180, in _get_arguments
    messages = run_sync(llm_call)
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\marvin\utilities\async_utils.py", line 69, in run_sync
    return asyncio.run(coroutine)
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\marvin\engine\executors\base.py", line 34, in start
    response = await self.step(messages)
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\marvin\engine\executors\base.py", line 45, in step
    llm_response = await self.run_engine(messages=messages)
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\marvin\engine\executors\openai.py", line 63, in run_engine
    llm_response = await self.model.run(
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\marvin\engine\language_models\openai.py", line 162, in run
    response = await openai.ChatCompletion.acreate(
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\openai\api_resources\chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate    response, _, api_key = await requestor.arequest(
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\openai\api_requestor.py", line 382, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\openai\api_requestor.py", line 726, in _interpret_async_response
    self._interpret_response_line(
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Unrecognized request argument supplied: functions
```

**Comment by zzstoatzz** [comment]
hey @TheodorosGalanos - i think this is because the model you're pointing at doesn't support function calling

[here's](https://stackoverflow.com/questions/76543136/how-to-do-function-calling-using-azure-openai) some discussion on your error that might be helpful

looks like maybe you want
```
MARVIN_AZURE_OPENAI_LLM_MODEL=gpt-35-turbo-0613
MARVIN_AZURE_OPENAI_API_VERSION=2023-07-01-preview
```

**Comment by TheodorosGalanos** [comment]
Alright that helps! I had tried this preview earlier but wasn't available nice to see it available now!

Now the error trace is:

```python
Traceback (most recent call last):
  File "C:\Users\theodoros.galanos\OneDrive - Aurecon Group\Projects\Ongoing\LLMOps\Prototypes\marvin\tests.py", line 37, in <module>
    Location("The Big Apple")
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\marvin\components\ai_model.py", line 266, in init_wrapper
    return original_init(
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\marvin\components\ai_model.py", line 80, in __init__
    kwargs = self.__class__.extract(
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\marvin\components\ai_model.py", line 130, in extract
    arguments = cls._get_arguments(
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\marvin\components\ai_model.py", line 180, in _get_arguments
    messages = run_sync(llm_call)
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\marvin\utilities\async_utils.py", line 69, in run_sync
    return asyncio.run(coroutine)
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\marvin\engine\executors\base.py", line 34, in start
    response = await self.step(messages)
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\marvin\engine\executors\base.py", line 45, in step
    llm_response = await self.run_engine(messages=messages)
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\marvin\engine\executors\openai.py", line 63, in run_engine
    llm_response = await self.model.run(
  File "C:\Users\theodoros.galanos\AppData\Roaming\Python\Python310\site-packages\marvin\engine\language_models\openai.py", line 185, in run
    content=msg.pop("content"),
KeyError: 'content'
```

**Comment by zzstoatzz** [comment]
@TheodorosGalanos huh! that is surprising. If you're willing, I'd be really curious what you see if you were to go into the site packages and `print(msg)` after line 179 of `marvin.engine.language_models.openai`

i would think the message structure would be consistent between azure and regular openai 🤔 

i'll do some more digging

**Comment by TheodorosGalanos** [comment]
Nice that works! The basic example on github now works! I'll keep going and let you know if anything else pops up.
Cheers!

**Comment by zzstoatzz** [comment]
@TheodorosGalanos great to hear 🙂 - thanks for working through this with me!

**Review by zzstoatzz — APPROVED** [review]

**Comment by jlowin** [comment]
Thanks @zzstoatzz and @TheodorosGalanos!

**Pull request merged**
